query SearchResultsBeer($query: String, $order: SearchOrder, $first: Int) {
  results: beerSearch(query: $query, order: $order, first: $first) {
    items {
      beer {
        id
        name
        style {
          id
          name
        }
        overallScore
        styleScore
      }
    }
  }
}
